trigger:
  - main  # Replace with your branch name

pool:
 vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

variables:
 POSTMAN_ENVIRONMENT: 'path/to/your/postman_environment.json'  #Export your environment and set path to folder with it
 GLOBALS_FILE_PATH: 'path/to/your/postman_globals.json'  #Export your globals and set path to folder with it
 REPORT_DIR: '$(Build.ArtifactStagingDirectory)/reports'  # Directory where the report will be saved
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.3.0'  # Specify the Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install -g newman
    npm install -g newman-reporter-html
  displayName: 'Install Newman and HTML Reporter'

- script: | 
    newman -v
  displayName: 'Verify Newman installation'

- script: |
    mkdir -p $(REPORT_DIR)
    newman run $(POSTMAN_COLLECTION) \
    --environment=$(POSTMAN_ENVIRONMENT) \
    --globals=$(GLOBALS_FILE_PATH) \
    --reporters html,json \
    --reporter-html-export $(REPORT_DIR)/newman-report.html \
    --reporter-json-export $(REPORT_DIR)/newman-report.json
  displayName: 'Run Newman with Postman Collection'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(REPORT_DIR)'  # Path to the report directory
    artifact: 'newman-reports'
    publishLocation: 'pipeline'
  displayName: 'Publish Newman Reports'