name: GitHub Actions Demo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Test-Execution-Exercise:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: CPU checker
        - uses: sudo apt install cpu-checker

#      - name: Build the app
#        run: ./gradlew assembleDebug

#      - name: Upload apk
#        uses: actions/upload-artifact@v2
#        with:
#          name: debug apk
#          path: app/build/outputs/apk/debug/app-debug.apk



#      - name: Instrumentation Tests
#        id: testing
#        uses: reactivecircus/android-emulator-runner@v2
##        continue-on-error: true
#        with:
#          profile: SnappAA_API_30
##          emulator-build: 7425822
##          api-level: 30
##          target: google_apis
##          arch: x86
##          force-avd-creation: false
##          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
#          script: ./gradlew connectedCheck --stacktrace
