name: Android CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test-Execution-Exercise:
    strategy:
      matrix:
        android-apis: [31]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew

      - name: Assemble app debug variant
        run: ./gradlew assembleDebug

      - name: ADB kill server
        run: adb kill-server

      - name: ADB start server
        run: adb start-server

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run UI tests
        id: testing
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: false
        with:
          emulator-build: 6110076
          api-level: ${{ matrix.android-apis }}
#          target: google_apis
          arch: x86_64
          emulator-boot-timeout: 180
#          cores: 6
#          ram-size: 6144
#          heap-size: 1024
#          disk-size: 4086
#          disable-animations: true
#          enable-hw-keyboard: false
          force-avd-creation: true
#          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
#          script: ./gradlew connectedCheck --stacktrace
