name: Android CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test-Execution-Exercise:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Instrumentation Tests
        id: testing
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: false
        with:
          api-level: 30
          target: google_apis
          arch: x86
#          cores: 4
#          ram-size: 4096
#          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
          script: ./gradlew connectedCheck --stacktrace
